enable_node_exporter: True

# Prometheus setup
prometheus_version: 2.17.1
prometheus_config_dir: /monitoring/prometheus/conf
prometheus_db_dir: /monitoring/prometheus/db
prometheus_web_listen_address: "0.0.0.0:9090"
prometheus_config_file: "{{ playbook_dir }}/files/monitoring/prometheus/prometheus.yml.j2"
prometheus_alert_rules_files: "{{ playbook_dir }}/files/monitoring/prometheus/alert_rules/*.rules"
#prometheus_web_external_url: "https://monitoring.sanbi.ac.za"
prometheus_storage_retention: "90d"

# Grafana setup
grafana_version: "6.7.1"
grafana_instance: "monitor.sanbi.ac.za"
grafana_address: 0.0.0.0
grafana_port: 3000
grafana_logs_dir: /monitoring/grafana/
grafana_data_dir: /monitoring/grafana/
grafana_security: { admin_user: "{{ lookup('hashi_vault', 'secret=secret/ansible/grafana:username')}}", admin_password: "{{ lookup('hashi_vault', 'secret=secret/ansible/grafana:password')}}" }
grafana_database: { type: sqlite3 }
grafana_datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: 'http://{{ prometheus_web_listen_address }}'
    basicAuth: false

# Consol setup
consul_config_path: /monitoring/consul/
consul_configd_path: /monitoring/consul/conf.d
consul_data_path: /monitoring/consul/data
consul_node_role: bootstrap
consul_iface: enp2s0
consul_bind_address: "{{ ansible_all_ipv4_addresses | ipaddr('192.168.2.0/24') | first }}"
consul_ui: true

#alertmanager
#alertmanager_external_url: "{{inventory_hostname}}"
alertmanager_config_dir: "/monitoring/alertmanager/conf"
alertmanager_db_dir: "/monitoring/alertmanager/db"
alertmanager_external_url: http://monitor.sanbi.ac.za:9093/
alertmanager_config_file: "{{ playbook_dir }}/files/monitoring/alertmanager/alertmanager.yml.j2"
alertmanager_slack_channel: "#alerts"