---

- hosts: all
  become: true
  gather_facts: false
  pre_tasks:
    - name: Install python2 for Ansible
      raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
      register: output
      changed_when: output.stdout != ""
      tags:
        - presetup
    - name: Gathering Facts
      setup:
  roles:
    - role: ansible-role-common
      tags:
        - common

- hosts: remote
  become: true
  roles:
    - role: ansible-role-gateway
 
- hosts: database
  become: true
  roles:
  - role: ansible-role-mariadb
  tags:
    - database

- hosts: slurm
  become: true
  roles:
  - role: ansible-role-cephfs_client
  - role: ansible-role-slurm
  - role: ansible-role-cluster 
  tags:
    - slurm

- hosts: monitoring
  become: true
  roles:
    - role: cloudalchemy.ansible-prometheus
    - role: cloudalchemy.ansible-grafana
    - role: brianshumate.ansible-consul
  tags:
    - monitor_server

- hosts: jenkins
  become: true
  pre_tasks:
    - name: Set the java_packages variable (Ubuntu).
      set_fact:
        java_packages:
          - openjdk-8-jdk
    - name: update cache
      apt:
        update_cache: true
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
    - role: ansible-role-nginx
  post_tasks:
    # - file:
    #     path: /etc/nginx/sites-enabled
    #     state: directory
    - template:
        src: "{{ playbook_dir }}/files/nginx_jenkins.j2"
        dest: "/etc/nginx/conf.d/jenkins.conf"
    - service:
        name: nginx
        state: restarted
      
