---

#########################################################################################
#                                                                                       #
#  Pre-tasks:                                                                           #
#    - Installs python2 on all machines (for backwards compatibility with some roles).  #
#                                                                                       #
#  Tasks:                                                                               #
#    - Runs the common role against all servers in the inventory.                       #
#                                                                                       #
#########################################################################################
- hosts: all
  become: true
  gather_facts: false
  pre_tasks:
    - name: Install python2 for Ansible
      raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
      register: output
      changed_when: output.stdout != ""
      ignore_errors: True
      tags:
        - presetup
    - name: Gathering Facts
      setup:
  tags:
    - always

- hosts: all
  become: True
  roles:
  - role: ansible-role-common
  tags:
    - common
 
####################################################################
#                                                                  #
#  Tasks:                                                          #
#    - Provisions the mariadb server for most of SANBI's services  #
#                                                                  #
####################################################################
- hosts: database
  become: true
  roles:
  - role: ansible-role-mariadb
  tags:
    - database

#############################################
#                                           #
#  Tasks:                                   #
#    - Activates cephfs shares on machines  #
#    - Installs slurm and slurm drmaa       #
#    - Performs cluster machine tweaks      #
#                                           #
#############################################
- hosts: slurm
  become: true
  roles:
  - role: ansible-role-cephfs_client
  - role: ansible-role-slurm
  - role: ansible-role-cluster 
  tags:
    - slurm

###############################
#                             #
#  Tasks:                     #
#    - Installs prometheus    #
#    - Installs grafana       #
#    - Installs alertmanager  #
#                             #
###############################
- hosts: monitoring
  become: yes
  roles:
    - role: cloudalchemy.ansible-prometheus
    - role: cloudalchemy.ansible-grafana
    - role: cloudalchemy.ansible-alertmanager
  tags:
    - monitor_server

#############################################################################
#                                                                           #
#  Pre-tasks:                                                               #
#    - Creates a consul user and group for each machine                     #
#  Tasks:                                                                   #
#    - Ensures consul server and agent installed on all necessary machines  #
#                                                                           #
#############################################################################
- hosts: consul_instances
  become: yes
  pre_tasks:
  - name: Ensure consul group
    group:
      name: consul
      state: present
  - name: Ensure consul user
    user:
      name: consul
      groups: consul
      state: present
      create_home: no
  - set_fact:
      consul_services: "{{ consul_services_headnode if (headnode is defined) else consul_services}}"
  roles:
    - role: brianshumate.ansible-consul
  tags:
    - consul

####################################################################
#                                                                  #
#  Tasks:                                                          #
#    - Provisions the gate replacement (external ssh access box).  #
#                                                                  #
####################################################################
- hosts: remote
  become: true
  roles:
    - role: ansible-role-cephfs_client
    - role: ansible-role-gateway
  tags: remote

####
#  Pre-tasks
#    - Set variables and install packages
#  Tasks:
#    - Install java
#    - Install jenkins
#    - Install nginx
####
# - hosts: jenkins
#   become: true
#   pre_tasks:
#     - name: Set the java_packages variable (Ubuntu).
#       set_fact:
#         java_packages:
#           - openjdk-8-jdk
#     - name: update cache
#       apt:
#         update_cache: true
#   roles:
#     - role: geerlingguy.java
#     - role: geerlingguy.jenkins
#     - role: ansible-role-nginx
#   post_tasks:
#     # - file:
#     #     path: /etc/nginx/sites-enabled
#     #     state: directory
#     - template:
#         src: "{{ playbook_dir }}/files/nginx_jenkins.j2"
#         dest: "/etc/nginx/conf.d/jenkins.conf"
#     - service:
#         name: nginx
#         state: restarted
#   tags:
#     - jenkins
      
