{
 "title": "HPC Cluster",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "nodes", "query": ".*hpc.*" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes in Cluster",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum by (node) (consul_health_node_status{node=~'$nodes'}))"
    }
   ]
  },
  {
   "title": "Nodes Good",
   "type": "singlestat",
   "description": "Update the threshold whenever more nodes are added to match expected amount of compute nodes",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum by (node) (consul_health_node_status{node=~'$nodes'})) - sum(consul_health_node_status{node=~'$nodes',status!='passing'})"
    }
   ]
  },
  {
   "title": "Nodes Warn",
   "type": "singlestat",
   "description": "Update the threshold whenever more nodes are added to match expected amount of compute nodes",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(consul_health_node_status{node=~'$nodes',status='warning'})"
    }
   ]
  },
  {
   "title": "Nodes Maint",
   "type": "singlestat",
   "description": "Update the threshold whenever more nodes are added to match expected amount of compute nodes",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(consul_health_node_status{node=~'$nodes',status='maintenance'})"
    }
   ]
  },
  {
   "title": "Nodes Critical",
   "type": "singlestat",
   "description": "Update the threshold whenever more nodes are added to match expected amount of compute nodes",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(consul_health_node_status{node=~'$nodes',status='critical'})"
    }
   ]
  },
  {
   "title": "ROOTFS USAGE",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_free_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100)"
    }
   ]
  },
  {
   "title": "SWAP USAGE",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes"
    }
   ]
  },
  {
   "title": "AVG CPU SYSTEM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg (avg by (instance) (irate(node_cpu_seconds_total{instance=~\"$nodes\",mode=\"system\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "AVG CPU USER",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 2, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg (avg by (instance) (irate(node_cpu_seconds_total{instance=~\"$nodes\",mode=\"user\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "AVG CPU IOWAIT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg (avg by (instance) (irate(node_cpu_seconds_total{instance=~\"$nodes\",mode=\"iowait\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU (USER)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{instance=~\"$nodes\",mode=\"user\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MEM USED",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percent", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "100 - (((node_memory_MemFree_bytes{instance=~\"$nodes\"} + node_memory_Buffers_bytes{instance=~\"$nodes\"} + node_memory_Cached_bytes{instance=~\"$nodes\"}) / node_memory_MemTotal_bytes{instance=~\"$nodes\"}) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "10GbE NETWORK TRAFFIC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "(sum by (instance) (irate(node_network_receive_bytes_total{instance=~\"$nodes\", device!=\"lo\",device!~\"eno.*\",device!~\"eth.*\"}[5m]))) * 8",
     "legendFormat": "RECV: {{instance}}"
    },
    {
     "expr": "- (sum by (instance) (irate(node_network_transmit_bytes_total{instance=~\"$nodes\", device!=\"lo\",device!~\"eno.*\",device!~\"eth.*\"}[5m])) * 8)",
     "legendFormat": "TRANS: {{instance}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } }
 ]
}