{
 "title": "PfSense",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Thread Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by(chart)(netdata_cpu_cpu_percentage_average))",
     "legendFormat": "Cores"
    }
   ]
  },
  {
   "title": "Swap Free",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "netdata_system_swap_MiB_average{dimension=\"free\"}"
    }
   ]
  },
  {
   "title": "Load 1m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "netdata_system_load_load_average{dimension=\"load1\"}"
    }
   ]
  },
  {
   "title": "Load 5m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "netdata_system_load_load_average{dimension=\"load5\"}"
    }
   ]
  },
  {
   "title": "Load 15m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "netdata_system_load_load_average{dimension=\"load15\"}"
    }
   ]
  },
  {
   "title": "External Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "netdata_net_net_kilobits_persec_average{family=\"igb0\"}",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "netdata_system_cpu_percentage_average",
     "legendFormat": "{{dimension}}"
    }
   ]
  }
 ]
}